Added release 1.14.5 page
HDFGroup/HDFGroup.github.io pull request #316
Opened 2024-09-13 15:47 UTC by bmribler

2024-09-30 18:07 UTC, loricooperhdf commented on downloads/hdf5/hdf5_1_14_5.md
> +|| [Newsletter Announcement](https://www.hdfgroup.org/2024/09/release-of-hdf5-1-14-5-newsletter-/) |
URL will be  https://www.hdfgroup.org/2024/09/30/release-of-hdf5-1-14-5-newsletter-204/

2024-09-30 18:08 UTC, loricooperhdf commented on downloads/hdf5/hdf5_1_14_5.md
> +|| [API Compatibility Report between 1.14.4 and 1.14.5](https://github.com/HDFGroup/hdf5/releases/download/hdf5_1.14.5/hdf5-1.14.5.html.abi.reports.tar.gz) |
Tar and gzip for a couple of HTML files?

2024-09-30 18:09 UTC, loricooperhdf requested changes
See inline coments... and should this still be a draft PR?

2024-09-30 20:19 UTC, lkurz commented on downloads/hdf5/hdf5_1_14_5.md
> +|| [Software Changes from Release to Release](../../documentation/hdf5-docs/release_specifics/sw_changes_1.14.html) |
Should this page need to be updated for 1.14.5?

2024-09-30 20:39 UTC, lkurz commented on downloads/hdf5/hdf5_1_14_5.md
> +* `wget – wget https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.N/hdf5-1.N.N/src/<distribution>.tar.gz`
this wget command would pull from the OLD ftp archives. 
Github releases are not at that location.

A user could copy the the links from the Repo's Releases Assets  to use with wget.

2024-09-30 20:54 UTC, lkurz commented on downloads/hdf5/hdf5_1_14_5.md
> +|| [New Features in HDF5 Release 1.14](../../documentation/hdf5-docs/release_specifics/new_features_1_14.html) |
Is this file up to date?

2024-09-30 20:54 UTC, bmribler commented on downloads/hdf5/hdf5_1_14_5.md
> +|| [Software Changes from Release to Release](../../documentation/hdf5-docs/release_specifics/sw_changes_1.14.html) |
Working on it....

2024-09-30 20:58 UTC, lkurz commented on downloads/hdf5/hdf5_1_14_5.md
> +The new HDF5 documentation based on [Doxygen](https://www.doxygen.nl/index.html) is available [here]({{site.url_docs}}/releases/hdf5/latest-docs.html)
NO NEED to change this line, but I wanted to briefly document it's use. 

"{{site.url_docs}}" is not necessary for support site.  It is useful when working in a Codespace or a docker container dev environment.  Prepend it to a url which has a target at DOCS ( i.e.  releases/, archive/, ftp/, ) and then use the _config-local.yml, which has the variable set, when you start Jekyll server.  This keeps the 404's away.  Otherwise the variable is empty and doesn't affect the remainder of the url path.

2024-09-30 21:17 UTC, bmribler commented on downloads/hdf5/hdf5_1_14_5.md
> +|| [New Features in HDF5 Release 1.14](../../documentation/hdf5-docs/release_specifics/new_features_1_14.html) |
I think so

2024-09-30 21:18 UTC, bmribler commented on downloads/hdf5/hdf5_1_14_5.md
> +The new HDF5 documentation based on [Doxygen](https://www.doxygen.nl/index.html) is available [here]({{site.url_docs}}/releases/hdf5/latest-docs.html)
OK, I should put it back the way it was?

2024-09-30 21:33 UTC, lkurz commented on downloads/hdf5/hdf5_1_14_5.md
> +The new HDF5 documentation based on [Doxygen](https://www.doxygen.nl/index.html) is available [here]({{site.url_docs}}/releases/hdf5/latest-docs.html)
It's OK the way it is.  If fact preferable in the cases mentioned above.

2024-09-30 21:49 UTC, bmribler commented
I think I got all the requested changes (marked resolved) except new_features_1_14.html, which I will get to after feeding my mother, and the one from Lori, which I don't understand.  Could you please take a quick look to see if I missed anything else?

2024-09-30 22:43 UTC, lkurz commented on downloads/hdf5/hdf5_1_14_5.md
> +|| [Doxygen generated Reference Manual](https://docs.hdfgroup.org/releases/hdf5/latest-docs.html) |
change this url to 
https://support.hdfgroup.org/releases/hdf5/latest-docs.html

2024-10-01 00:24 UTC, bmribler commented on downloads/hdf5/hdf5_1_14_5.md
> +|| [API Compatibility Report between 1.14.4 and 1.14.5](https://github.com/HDFGroup/hdf5/releases/download/hdf5_1.14.5/hdf5-1.14.5.html.abi.reports.tar.gz) |
@loricooperhdf What do I need to do, Lori?

2024-10-01 00:30 UTC, bmribler commented
One more try, still not the one Lori commented though.

2024-10-01 05:38 UTC, bmribler commented
> See inline coments... and should this still be a draft PR?

@loricooperhdf Sorry, but I don't know what you're referring to.  Why should it still be a draft PR?

2024-10-01 05:50 UTC, bmribler commented
> > See inline coments... and should this still be a draft PR?
> 
> @loricooperhdf Sorry, but I don't know what you're referring to. Why should it still be a draft PR?

Wait, I think your comment above was before I made all the changes.  There is one question from you that I don't understand: "Tar and gzip for a couple of HTML files?"  Otherwise, I think I made all the requested changes.  Please let me know if I'm wrong, and thanks everyone!

2024-10-01 12:47 UTC, byrnHDF commented on documentation/hdf5-docs/release_specifics/new_features_1_14.md
The URLs here are correct

2024-10-01 12:50 UTC, byrnHDF commented on documentation/hdf5-docs/release_specifics/hdf5_1_14.md
> +* [16 bit floating point and Complex number datatypes](https://github.com/HDFGroup/hdf5doc/blob/master/RFCs/HDF5_Library/Float16/RFC__Adding_support_for_16_bit_floating_point_and_Complex_number_datat
This RFC needs to be moved to the https://support.hdfgroup.org/releases/hdf5/documentation/rfc location

2024-10-01 12:55 UTC, byrnHDF commented on documentation/hdf5-docs/release_specifics/sw_changes_1.14.md
>  * [Compatibility report for Release 1.14.3 versus Release 1.14.2](https://htmlpreview.github.io/?https://raw.githubusercontent.com/HDFGroup/hdf5doc/master/html/ADGuide/Compatibility_Report/hdf5-1.14.
These need to be moved under the releases

2024-10-01 13:02 UTC, byrnHDF commented on documentation/hdf5-docs/release_specifics/sw_changes_1.14.md
> +* [Compatibility report for Release 1.14.5 versus Release 1.14.4](https://github.com/HDFGroup/hdf5/releases/download/hdf5_1.14.5/hdf5-1.14.5.html.abi.reports.tar.gz)
Use support.hdfgroup.org

2024-10-01 13:13 UTC, loricooperhdf commented
> > > See inline coments... and should this still be a draft PR?
> > 
> > 
> > @loricooperhdf Sorry, but I don't know what you're referring to. Why should it still be a draft PR?
> 
> Wait, I think your comment above was before I made all the changes. There is one question from you that I don't understand: "Tar and gzip for a couple of HTML files?" Otherwise, I think I made all the requested changes. Please let me know if I'm wrong, and thanks everyone!

At the time I was looking at this PR, it was still marked as a draft. Disregard.

> https://github.com/HDFGroup/hdf5/releases/download/hdf5_1.14.4.2/hdf5-1.14.4-2.html.abi.reports.tar.gz

I don't understand we have provided these as .tar.gz when it's just a few html pages. I don't think that's how we did it in the past. Why not just link to a HTML page with links to the other HTML pages?

2024-10-01 13:31 UTC, bmribler commented
> > > > See inline coments... and should this still be a draft PR?
> > > 
> > > 
> > > @loricooperhdf Sorry, but I don't know what you're referring to. Why should it still be a draft PR?
> > 
> > 
> > Wait, I think your comment above was before I made all the changes. There is one question from you that I don't understand: "Tar and gzip for a couple of HTML files?" Otherwise, I think I made all the requested changes. Please let me know if I'm wrong, and thanks everyone!
> 
> At the time I was looking at this PR, it was still marked as a draft. Disregard.
> 
Great, thanks!

> > https://github.com/HDFGroup/hdf5/releases/download/hdf5_1.14.4.2/hdf5-1.14.4-2.html.abi.reports.tar.gz
> 
> I don't understand we have provided these as .tar.gz when it's just a few html pages. I don't think that's how we did it in the past. Why not just link to a HTML page with links to the other HTML pages?

Ah!  Right, in the past the HTML files were in hdf5doc.  Allen is putting them in downloads now.

2024-10-01 14:03 UTC, bmribler commented on documentation/hdf5-docs/release_specifics/hdf5_1_14.md
> +* [16 bit floating point and Complex number datatypes](https://github.com/HDFGroup/hdf5doc/blob/master/RFCs/HDF5_Library/Float16/RFC__Adding_support_for_16_bit_floating_point_and_Complex_number_datat
Done

2024-10-01 14:08 UTC, byrnHDF approved these changes

2024-10-01 15:00 UTC, loricooperhdf commented on documentation/hdf5-docs/release_specifics/hdf5_1_14.md
> +* [16 bit floating point and Complex number datatypes](https://github.com/HDFGroup/hdf5doc/blob/master/RFCs/HDF5_Library/Float16/RFC__Adding_support_for_16_bit_floating_point_and_Complex_number_datat
This might be me not following the changes, but should the URL of this RFC be different?

2024-10-01 15:03 UTC, loricooperhdf commented on downloads/hdf5/hdf5_1_14_5.md
> +|| [API Compatibility Report between 1.14.4 and 1.14.5](https://github.com/HDFGroup/hdf5/releases/download/hdf5_1.14.5/hdf5-1.14.5.html.abi.reports.tar.gz) |
https://github.com/HDFGroup/hdf5/releases/download/hdf5_1.14.5/hdf5-1.14.5.html.abi.reports.tar.gz 

So we change this link, right? I thought I saw a new URL elsewhere?

2024-10-01 15:22 UTC, bmribler commented on downloads/hdf5/hdf5_1_14_5.md
> +|| [API Compatibility Report between 1.14.4 and 1.14.5](https://github.com/HDFGroup/hdf5/releases/download/hdf5_1.14.5/hdf5-1.14.5.html.abi.reports.tar.gz) |
Hmm, yes, I did.  This one is outdated.

2024-10-01 15:22 UTC, byrnHDF commented on downloads/hdf5/hdf5_1_14_5.md
> +|| [API Compatibility Report between 1.14.4 and 1.14.5](https://github.com/HDFGroup/hdf5/releases/download/hdf5_1.14.5/hdf5-1.14.5.html.abi.reports.tar.gz) |
That is the link to all four - we added a subdir in compat_report that is uncompressed

2024-10-01 15:39 UTC, loricooperhdf approved these changes

2024-10-01 15:39 UTC, merged